version: '3'

services:
  web: &web
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker
    restart: always
  rabbitmq:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  celery_worker:
    <<: *web
    command: celery -A bostonGene worker -l info
    ports: []
    depends_on:
      - rabbitmq
    restart: always
