# Generated by Django 2.2.7 on 2019-12-04 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('md5_sum', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Done', 'The task is completed.'), ('in progress', 'The task is in progress.'), ('fail', 'The task is failed.'), ('not exist', 'The task does not exist.')], default='in progress', max_length=30)),
            ],
        ),
    ]
